version: "3"

services:
  db:
    image: mysql
    restart: always
    command: mysqld --default-authentication-plugin=mysql_native_password
    env:
      MYSQL_ROOT_PASSWORD=secret
      MYSQL_DATABASE=nanocity
      MYSQL_USER=nanodev
      MYSQL_PASSWORD=nanodev
    volumes:
      - var:/data/db
    ports:
      - 3301:3306
  mail:
    image: maildev/maildev
    ports:
      - 1080:1080
      - 1025:1025
volumes:
  var:
